version: '3.8'
services:
  postgres:
    image: postgres:16
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"