spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123
  liquibase:
    change-log: classpath:db/changelog/changelog.xml
    default-schema: cs_schema
